export const MOBILE_MENU_TRANSITION_DURATION_MS = 480;
export const MOBILE_MENU_TRANSITION_DURATION_CLASS = 'duration-[480ms]';
export const MOBILE_MENU_TRANSITION_EASING_CLASS =
  'ease-[cubic-bezier(0.2,0,0,1)]';
export const MOBILE_MENU_CLOSE_DELAY_MS = MOBILE_MENU_TRANSITION_DURATION_MS + 40;
